name: Deploy Pages 

on:
  push:
    branches: [main]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkoutS
      uses: actions/checkout@v3
    - name: dependencies
      run: yarn --cwd doku install --frozen-lockfile
    - name: build
      run: yarn --cwd doku/docs docs:build

