name: Build and Deploy Docs

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: dependencies
      run: yarn --cwd doku
    - name: Build VuePress site
      run: yarn --cwd doku/docs docs:build
    # - name: vuepress-deploy
    #   uses: jenkey2011/vuepress-deploy@master
    #   env:        
    #     TARGET_BRANCH: gh_pages
    #     BUILD_SCRIPT: yarn --cwd doku/docs docs:build
    #     BUILD_DIR: doku/docs/.vuepress/dist/  
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: doku/docs/.vuepress/dist
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}