name: Build and Deploy Docs

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - run: yarn --cwd doku/docs docs:build      
    - name: deploy 
      uses: crazy-max/ghaction-github-pages@v2
      with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: /doku/docs/.vuepress/dist
        env:          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    