name: Build and Deploy Docs

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: oarchner/pdal-workshop
        TARGET_BRANCH: gh_pages
        BUILD_SCRIPT: yarn && yarn --cwd doku/docs docs:build
        BUILD_DIR: doku/docs/.vuepress/dist/  
 
